[build]
command = "cd exampleSite && hugo --themesDir ../.."
publish = "exampleSite/public"

[build.environment]
HUGO_VERSION = "0.79.0"
HUGO_BASEURL = "/"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404 