[build]
publish = "exampleSite/public"
command = "hugo server --source=exampleSite"

[build.environment]
HUGO_VERSION = "0.92.0"
HUGO_THEME = "repo"
HUGO_BASEURL = "https://academialight.netlify.app"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404 